app:
  name: Accounts
  host: accounts.biola.edu

cas:
  url: "https://login.biola.edu/cas"

email:
  from: no-reply@biola.edu
  smtp:
    server: postfix.biola.edu

sentry:
  url: # Set in settings.local.yml

password:
  min_length: 8
