app:
  name: Accounts
  host: accounts.biola.edu

users:
  new_before: 2592000 # 30 days
  reject_email_domain: "@biola.edu"

secret_token: # Set in settings.local.yml

cas:
  url: "https://login.biola.edu/cas"

trogdir:
  scheme: http
  host: trogdir-api.dev
  port:
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml
  api_timeout: 300 # 5 min

email:
  from: no-reply@biola.edu
  smtp:
    server: postfix.biola.edu

sentry:
  url: # Set in settings.local.yml

password:
  min_length: 8
  reset_expire: 86400 # 1 day

urn_namespaces:
  - "urn:biola:apps:gatekeeper:"
  - "urn:biola:apps:all:"
