app:
  name: Accounts
  host: accounts.biola.edu

users:
  new_before: 2592000 # 30 days
  reject_email_domain: "@biola.edu"

secret_token: # Set in settings.local.yml

cas:
  url: "https://login.biola.edu/cas"

email:
  from: no-reply@biola.edu
  smtp:
    server: postfix.biola.edu

sentry:
  url: # Set in settings.local.yml

password:
  min_length: 8

urn_namespaces:
  - "urn:biola:apps:gatekeeper:"
  - "urn:biola:apps:all:"
